### ISSUE TITLE
Reusable table

### ISSUE THREAD

**Issue by suriyaJaay** [muhimasri/angular-editable-table#2]
Hi @muhimasri  do you have any idea about creating reusable custom table with Add| Edit| Delete actions?

Thanks

**Comment by muhimasri** [comment]
Hi @suriyaJaay, thanks for opening an issue. This repository was intended to demonstrate how to create editable fields using dynamic schema but can be easily extended to enable adding and/or deleting rows. To add a new row, you can create a button and define a function in the controller to add an empty object to the data source:

```
addItem() {
    const newObj: any = {"name": "", "occupation": "", "dateOfBirth": "1984-05-05", "age": 0};
    this.dataSource = [...this.dataSource, newObj];
  }
```

Then the user can input information in the new row.

Since this is part of the article I created, I will look into adding a new section to how to add and delete objects.

Stay tuned!
Cheers

**Comment by muhimasri** [comment]
Hi @suriyaJaay, the latest code in this repository now has support to add, delete and edit actions from API services. Also, this article has a step-by-step guide to creating an editable table.

https://muhimasri.com/blogs/add-and-remove-table-rows-using-angular-material/
